version: '2'

services:
  app:
    build: .
    image: ignibase
    command: amber watch
    environment:
      DATABASE_URL: sqlite3:./db/ignibase_development.db
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

  migrate:
    build: .
    image: ignibase
    command: bash -c 'amber db migrate seed'
    environment:
      DATABASE_URL: sqlite3:./db/ignibase_development.db
    volumes:
      - .:/app
    links:
      - db


volumes:
  db:
  nodes:
  shards:
