defaults : &defaults
  host: localhost
  adapter: postgres
  user: postgres
  password: ""
  migration_files_path: db/migrations # this is the default location for all migrations

development:
  db: igni_dev
  <<: *defaults

test:
  db: igni_test
  <<: *defaults

production:
  db: igni_production
  <<: *defaults